import React from 'react';
import {
  // Existing
  User,
  Heart,
  Users,
  Briefcase,
  GraduationCap,
  HeartHandshake,
  Headphones,
  Smile,
  Lock,
  Award,
  Sparkles,
  Calendar,
  Phone,
  MapPin,
  Globe,
  Send,
  ChevronDown,
  ChevronUp,
  Check,
  Info,
  Clock,
  Facebook,
  Instagram,
  Linkedin,
  Menu,
  X,
  AlertCircle,
  HelpCircle,
  TrendingUp,
  HeartCrack,
  ShieldCheck,
  CheckCircle2,
  CalendarDays,
  Target,
  MessageSquareShare,
  Coins,
  MessageSquare,
  Bot,
  ExternalLink,
  Maximize2,
  ChevronLeft,
  Plus,
  Mic,
  Map,
  ArrowUp,
  RefreshCw,
  ChevronRight,
  Download,
  Search,
  Hash,
  Home,
  BookOpen,
  Handshake,
  QrCode,
  ArrowLeft,
  UserCircle,
  Mail,
  // Previously missing — navigation & arrows
  ArrowRight,
  // Previously missing — auth
  AlertTriangle,
  LogIn,
  LogOut,
  UserPlus,
  LockKeyhole,
  // Previously missing — calendar / appointments
  CalendarCheck,
  CalendarPlus,
  CalendarX2,
  // Previously missing — status
  CheckCheck,
  CheckCircle,
  XCircle,
  History,
  // Previously missing — UI
  Eye,
  Loader2,
  LayoutDashboard,
  CreditCard,
  Scale,
  Zap,
  // Previously missing — content
  FileText,
  Video,
  // Previously missing — people / professions
  UserRound,
  Stethoscope,
  // Previously missing — data / stats
  Activity,
  LineChart,
  BrainCircuit,
  Brain,
  Microscope,
  LifeBuoy,
  // Previously missing — org / social
  Building2,
  Share2,
  ClipboardCheck,
} from 'lucide-react';

const iconMap = {
  // Existing
  User,
  Heart,
  Users,
  Briefcase,
  GraduationCap,
  HeartHandshake,
  Headphones,
  Smile,
  Lock,
  Award,
  Sparkles,
  Calendar,
  Phone,
  MapPin,
  Globe,
  Send,
  ChevronDown,
  ChevronUp,
  Check,
  Info,
  Clock,
  Facebook,
  Instagram,
  Linkedin,
  Menu,
  X,
  AlertCircle,
  HelpCircle,
  TrendingUp,
  HeartCrack,
  ShieldCheck,
  CheckCircle2,
  CalendarDays,
  Target,
  MessageSquareShare,
  Coins,
  MessageSquare,
  Bot,
  ExternalLink,
  Maximize2,
  ChevronLeft,
  Plus,
  Mic,
  Map,
  ArrowUp,
  RefreshCw,
  ChevronRight,
  Download,
  Search,
  Hash,
  Home,
  BookOpen,
  Handshake,
  QrCode,
  ArrowLeft,
  UserCircle,
  Mail,
  // Added
  ArrowRight,
  AlertTriangle,
  LogIn,
  LogOut,
  UserPlus,
  LockKeyhole,
  CalendarCheck,
  CalendarPlus,
  CalendarX2,
  CheckCheck,
  CheckCircle,
  XCircle,
  History,
  Eye,
  Loader2,
  LayoutDashboard,
  CreditCard,
  Scale,
  Zap,
  FileText,
  Video,
  UserRound,
  Stethoscope,
  Activity,
  LineChart,
  BrainCircuit,
  Brain,
  Microscope,
  LifeBuoy,
  Building2,
  Share2,
  ClipboardCheck,
};

export type IconName = keyof typeof iconMap;

interface LucideIconProps {
  name: string;
  className?: string;
  size?: number | string;
  strokeWidth?: number;
}

export default function LucideIcon({ name, className = '', size, strokeWidth }: LucideIconProps) {
  // Safe lookup with a fallback icon
  const IconComponent = iconMap[name as IconName] || HelpCircle;
  return <IconComponent className={className} size={size} strokeWidth={strokeWidth} />;
}
